### ISSUE TITLE
Setup gradle build scripts for creating JAR and uploading to Bintray

### ISSUE THREAD

**Issue by vanshg** [nkansal96/aurora-java#14]
- Will need to create an Aurora org on Bintray

**Comment by nkansal96** [comment]
[Bintray](https://bintray.com) doesn't seem to be free and while we probably want to upload the JAR there eventually, is there a free-er alternative similar to npmjs? What are your thoughts on the Maven central repository? The [Stripe SDK](https://search.maven.org/#artifactdetails%7Ccom.stripe%7Cstripe-java%7C5.36.0%7Cjar) is uploaded there.

**Comment by vanshg** [comment]
Sorry to be more specific, we will have to use the jCenter feature of Bintray. I've actually uploaded multiple [libraries](http://jcenter.bintray.com/com/vanshgandhi/) via jCenter so I can confirm that it is free. They also have an option to sync all uploads with Maven Central as well. Also, jCenter is the default Maven repo used by Android Studio (which uses Java for it's development) and IntelliJ so I think it'd be in our best interest to use jCenter/Bintray

(Stripe also has their library on jCenter http://jcenter.bintray.com/com/stripe/stripe-java/)

**Comment by nkansal96** [comment]
Okay! I didn't see jCenter. I created an account. Let me know if I created the repository correctly: https://bintray.com/auroraapi/aurora-java

**Comment by vanshg** [comment]
Ah, looks like you've created a repository. We need to create a Maven package instead

**Comment by nkansal96** [comment]
Is the package inside this repository?

**Comment by vanshg** [comment]
The package should be placed in the Maven repository, not a custom one

**Comment by vanshg** [comment]
Resolved in https://github.com/nkansal96/aurora-java/pull/19
