### ISSUE TITLE
Trimming beginning silence

### ISSUE THREAD

**Issue by nkansal96** [nkansal96/aurora-java#22]
In reference to [this](https://github.com/nkansal96/aurora-java/blob/ea4c5ae9986154206eb08130811b8579cda16eeb/src/main/java/com/auroraapi/models/Audio.java#L102), I noticed that the silence is continuously accumulated until some noise is made, however there is no limit to the amount of data in the silence buffer. Would it be possible to make this in line with the [python implementation](https://github.com/auroraapi/aurora-python/blob/d092c9373648931def728e90fa84048a08849b44/auroraapi/audio.py#L181) which keeps the last 32 buffers worth of silence instead of all of it?

This should be the same behavior for the timed record as well – it should not start the timer (and should accumulate silence in the same way) while there is silence.

**Comment by vanshg** [comment]
Fixed with https://github.com/nkansal96/aurora-java/commit/65363ba1f13e2675ab4f0721be8cf8ca79c48a9c, https://github.com/nkansal96/aurora-java/commit/a602468ecac526fd075d5bc2f8dda9d192483638, and https://github.com/nkansal96/aurora-java/commit/5f0c38443969e27f3a385728b103b457c7960b48
