### ISSUE TITLE
Create Javadoc comments for all public methods

### ISSUE THREAD

**Issue by vanshg** [nkansal96/aurora-java#9]
All the public methods should have Javadoc comments that inform the developer of functionalities, parameters, and return types

Look at the `returnOrThrow` in `Aurora.java` (https://github.com/nkansal96/aurora-java/blob/master/src/main/java/com/auroraapi/Aurora.java#L82) for what it should look like.

**Comment by epicchewy** [comment]
resolved in https://github.com/nkansal96/aurora-java/pull/17
